#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config external_bar                 all:12:0
# yabai -m config mouse_follows_focus        on
# yabai -m config focus_follows_mouse        autofocus
yabai -m config window_placement             second_child
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config insert_feedback_color        0x00FFFFFF
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12

# check number of windows in space
# if there is 0 or 1 window(s), set layout to bsp
# if there are more than one window, set window layout to stack
yabai -m signal --add event=window_created action='/Users/landoncrabtree/.config/yabai/auto.sh $YABAI_WINDOW_ID'
yabai -m signal --add event=window_destroyed action='/Users/landoncrabtree/.config/yabai/auto.sh $YABAI_WINDOW_ID'
yabai -m signal --add event=window_moved action='/Users/landoncrabtree/.config/yabai/auto.sh $YABAI_WINDOW_ID'


# yabai -m signal --add event=window_created action='
#   yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || \
#   yabai -m window $YABAI_WINDOW_ID --toggle float && \
#   yabai -m window $YABAI_WINDOW_ID --layer above && \
#   yabai -m window $YABAI_WINDOW_ID --grid 3:3:1:1:1:1
# '


# rules
## makes system preferences always floating
yabai -m rule --add app="^System Settings$" manage=off

# Refresh yabai if a tab in finder or terminal is created or moved to new window
# https://github.com/koekeishiya/yabai/issues/68
# yabai -m signal --add event=window_created app="^Terminal$|^Finder$" \
#     action="yabai -m space --focus next && yabai -m space --focus recent"

# yabai -m signal --add event=window_destroyed app="^Terminal$|^Finder$" \
#     action="yabai -m space --focus next && yabai -m space --focus recent"

# yabai -m signal --add event=window_moved app="^Terminal$|^Finder$" \
#     action="yabai -m space --focus next && yabai -m space --focus recent"

# yabai -m signal --add event=window_resized app="^Terminal$|^Finder$" \
#     action="yabai -m space --focus next && yabai -m space --focus recent"


echo "yabai configuration loaded.."
