eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export GEMSDIR=$(gem environment gemdir)/bin
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"
export PATH="$GEMSDIR:$PATH"
export PATH="$PATH:/opt/homebrew/opt/binutils/bin"
export PATH="$PATH:/opt/homebrew/opt/john-jumbo/share/john"
export PATH="$PATH:$HOME/.gem/bin"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"

# export CFLAGS="-I/opt/homebrew/include -L/opt/homebrew/lib"
export COPY_CLIPBOARD=TRUE